AWSTemplateFormatVersion: '2010-09-09'
Description: Creazione di una VPC con una due subnet.Creazione di un gruppo di Autoscaling con istanze EC2 che supportano Apache e PHP.
Creazione di un Application Load Balancer (ALB) collegato a un gruppo di Autoscaling EC2.

Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true

  Subnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: "us-east-1a"
      MapPublicIpOnLaunch: true

  Subnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: "us-east-1b"
      MapPublicIpOnLaunch: true

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref MyVPC
      InternetGatewayId: !Ref InternetGateway

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MyVPC

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: VPCGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  SubnetsRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: 
        - !Ref Subnet1
        - !Ref Subnet2
      RouteTableId: !Ref PublicRouteTable

  MyLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: ami-0abcdef1234567890
      InstanceType: t2.micro      
      SecurityGroups:
        - !Ref EC2InstancesSecurityGroup    
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
  
  EC2InstancesSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: EC2InstancesSecurityGroup
      Description: "Allow HTTP and HTTPS traffic"
      GroupName: !Ref MYLaunchConfiguration
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0

  LoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ALB Security Group
      Vpc: !Ref MyVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0          

  MyLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Subnets:
        - !Ref MySubnet1   
        - !Ref MySubnet2
      SecurityGroups:
        - !Ref LoadBalancerSecurityGroup   
      Type: application   

  MyTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Vpc: !Ref MyVPC   
      Port: 80           
      Protocol: HTTP     
      HealthCheckIntervalSeconds: 30
      HealthCheckProtocol: HTTP
      HealthCheckPath: /health   

  MyListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref MyLoadBalancer   
      Protocol: HTTP     
      Port: 80           
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref MyTargetGroup  

  KeyName: "DevOpsDemo"
      Tags:
        - Key: "Name"
          Value: "Gianluca"
        - Key: "Cognome"
          Value: "ScottodAbusco"
        - Key: "Environment"
          Value: "DevOpsAcademy"  

 Outputs:
  ALBEndpoint:
    Description: "Application Load Balancer endpoint"
    Value: !GetAtt MyALB.DNSName
