AWSTemplateFormatVersion: '2010-09-09'
Description: Creazione di una VPC con una due subnet,creazione di un gruppo di Autoscaling con istanze EC2 che supportano Apache e PHP,creazione di un Application Load Balancer (ALB) collegato a un gruppo di Autoscaling EC2

Parameters:
#  AMI:
#    Type: String

#  InstanceType:
#    Type: String

  AMI:
    Description: Amazon Machine Image ID
    Type: String
    Default: "ami-06935448000742e6b"

  InstanceTypeParameter:
    Type: String
    Default: "t2.micro"
    AllowedValues:  
      - t2.small
      - t2.micro
      - t2.large 
      
Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: "Name"
          Value: "Gianluca"
        - Key: "Cognome"
          Value: "ScottodAbusco"
        - Key: "Environment"
          Value: "DevOpsAcademy"  

  Subnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: "us-west-2a"
      MapPublicIpOnLaunch: true
      Tags:
        - Key: "Name"
          Value: "Subnet1"
        - Key: "Environment"
          Value: "DevOpsAcademy"  

  Subnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: "us-west-2b"
      MapPublicIpOnLaunch: true
      Tags:
        - Key: "Name"
          Value: "Subnet2"
        - Key: "Environment"
          Value: "DevOpsAcademy" 

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: "MyInternetGateway"

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref MyVPC
      InternetGatewayId: !Ref InternetGateway

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MyVPC

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: VPCGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  SubnetsRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: 
        - !Ref Subnet1
        - !Ref Subnet2
      RouteTableId: !Ref PublicRouteTable
      
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group per le istanze EC2
      VpcId: !Ref MyVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  MyLaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: !Ref AMI
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref MySecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y httpd php php-mysql
          systemctl enable httpd
          systemctl start httpd
          echo "<?php phpinfo(); ?>" > /var/www/html/index.php
          chkconfig httpd on

  MyAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      LaunchConfigurationName: !Ref MyLaunchConfig
      MinSize: "2"
      MaxSize: "5"
      DesiredCapacity: "2"
      VPCZoneIdentifier:
        - !Ref Subnet1  
        - !Ref Subnet2         

  MyLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Subnets:
        - !Ref Subnet1   
        - !Ref Subnet2
      SecurityGroups:
        - !Ref MySecurityGroup   
      Type: application   

  MyTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: MyTargetGroup
      VpcId: !Ref MyVPC
      TargetType: instance
      Port: 80           
      Protocol: HTTP     
      HealthCheckIntervalSeconds: 30
      HealthCheckProtocol: HTTP
      HealthCheckPath: /health   
      Tags:
        - Key: Nome
          Value: "Gianluca"
        - Key: Cognome
          Value: "ScottodAbusco"
        - Key: Environment
          Value: DevOpsAcademy
          
  MyListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref MyLoadBalancer   
      Protocol: HTTP     
      Port: 80           
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref MyTargetGroup  

Outputs:
  ALBEndpoint:
    Description: "Load Balancer endpoint URL"
    Value: !GetAtt MyLoadBalancer.DNSName
